# PyTorch チュートリアル
本テキストでは、PyTorchの基本文法について説明します。PyTorchには特有のテンソル型があり、基本的にこのテンソル型を用いて演算を行います。テンソルは、NumPyのndarrayと類似していますが、GPUによる高速演算が可能であるという特徴があります。また、GPUを用いることで計算効率を向上させられますが、GPUの使用を明示的に指定する必要があるといった特徴があります。本テキストでは、上記の事柄を中心に説明します。

# 目次
1. テンソル:Tensorsとは
1. 基本演算
2. TensorとNumPyの相互変換
  - TensorからNumPyへの変換
  - TensorからNumPyへの変換
3. GPUとCPUの使い分け

# 1. テンソル：Tensorsとは

テンソルは特殊なデータ構造で、配列や行列によく似ています。

PyTorchではテンソル型の変数を使用して、モデルの入力と出力、そしてモデルのパラメータを表現します。


テンソルは[NumPy](https://numpy.org/)のndarraysに似ていますが、GPU利用による高速化が可能で、本資料での解説は行いませんが「自動微分」用のパラメータが追加されている点で異なっています。

テンソルとNumPyの配列は基本的には同じメモリを共有することができるため、2つの型間での変換時にはデータをコピーする必要がありません。






NumPyのndarraysに慣れている人は、Tensor APIをすぐに使いこなせると思います。

そうでない場合には、本チュートリアルを通してぜひ習得してください。

# 2. 基本演算

In [ ]:
import torch
import numpy as np

## テンソルの初期化


テンソルは様々な手法で初期化できます。

以下に例を示します。



**テンソルの作成**

テンソルを作成するには、次のようにしますが、この方法では中身は初期化されていないことに注意してください。

In [ ]:
import torch
x = torch.empty(5, 3)
x

tensor([[4.7799e-22, 3.0854e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0854e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 8.9205e-23]])

**データから直接テンソルに変換**

データから直接テンソルを作ることができます。

その際、データ型は自動的に推測されます。


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**NumPy arrayからテンソルに変換**

テンソルとNumpy arraysは相互に変換可能です。



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**他のテンソルから作成**

他のテンソルから新しいテンソルを作成する場合、明示的に上書きされない限り、引数のテンソルのプロパティ（形状、データ型）を保持します。その場合、_likeがつく関数を使用します。


In [ ]:
x_ones = torch.ones_like(x_data) # x_dataの特性（プロパティ）を維持
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_dataのdatatypeを上書き更新
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6887, 0.9360],
        [0.9095, 0.8902]]) 



**ランダム値や定数のテンソルの作成**


``shape``は、テンソルの次元を示すタプルです。

以下の例では、shapeからテンソルのサイズを決めています。





In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8197, 0.7803, 0.5036],
        [0.5415, 0.5585, 0.6357]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.tensor([4, 3])
x

tensor([4, 3])

大きさを知るには、sizeメソッドを呼び出します。

In [ ]:
x.size()

torch.Size([2])

型を知るだけであれば、typeメソッドを使用します。

In [ ]:
type(x)

torch.Tensor

整数を要素に持つテンソルと、浮動小数点を要素に持つテンソルをそれぞれ作成して違いを確認しましょう。


In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x.type()

'torch.LongTensor'

In [ ]:
x = torch.FloatTensor([1, 2, 3, 4, 5, 6])
x.type()

'torch.FloatTensor'

次の大文字Tensorと小文字tensorの違いに注意してください。
大文字Tensorは浮動小数点型、小文字tensorは整数型です。

In [ ]:
x = torch.Tensor([1, 2, 3, 4, 5, 6])
x.type()

'torch.FloatTensor'

## テンソルの属性変数



テンソルは属性変数として、その形状、データの型、保存されているデバイスを保持しています。


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## テンソルの操作


PyTorchでは、算術、線形代数、行列操作（転置、インデックス、スライス）など、100種類以上のテンソル演算が可能です。フーリエ変換、逆行列など多くの演算が可能となっています。

種々操作の詳細は[こちら](https://pytorch.org/docs/stable/torch.html)
をご覧ください。





テンソル操作の中からいくつかを試してみましょう。

テンソルの操作方法は、NumPyの操作方法に類似しているため、NumPyに慣れている人は、テンソルの操作も容易かと思います。




**インデックスとスライス**



In [ ]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


numpyと同様の方法で、行を入手するには以下のように記述します。

In [ ]:
x = torch.rand(5, 3)
print(x) 
print(x[1]) # 2行めの入手

tensor([[0.4406, 0.2965, 0.9079],
        [0.6862, 0.3601, 0.8544],
        [0.7490, 0.6419, 0.7057],
        [0.2902, 0.0737, 0.6788],
        [0.9286, 0.5344, 0.4114]])
tensor([0.6862, 0.3601, 0.8544])


同じように、列の入手は以下のように記述します。

In [ ]:
x = torch.rand(5, 3)
print(x) 
print(x[:,1]) #2列めの入手

tensor([[0.7546, 0.4525, 0.0076],
        [0.8726, 0.2029, 0.3650],
        [0.9411, 0.5154, 0.3957],
        [0.1645, 0.4130, 0.9437],
        [0.0831, 0.4594, 0.5817]])
tensor([0.4525, 0.2029, 0.5154, 0.4130, 0.4594])


部分要素を入手する場合には以下のように記述します。

In [ ]:
x = torch.rand(5, 5)
print(x)
x[2:4,1]

tensor([[0.2689, 0.5732, 0.1335, 0.1412, 0.1294],
        [0.6634, 0.3808, 0.4097, 0.9845, 0.6333],
        [0.1351, 0.2406, 0.4529, 0.7092, 0.9501],
        [0.1822, 0.6359, 0.6850, 0.9461, 0.2541],
        [0.7246, 0.6324, 0.2945, 0.8066, 0.6736]])


tensor([0.2406, 0.6359])

**行列のリサイズ**

PyTorchでテンソルを操作する関数は、transpose, view, reshapeがあります。


基本はtransposeでテンソルを転置する関数となっています。

In [ ]:
x = torch.rand(4, 3)
print(x)
y = torch.transpose(x, 0, 1) # 転置している
print(y)

tensor([[0.2573, 0.1386, 0.6858],
        [0.5918, 0.8789, 0.4690],
        [0.2013, 0.9312, 0.3803],
        [0.9897, 0.3238, 0.2955]])
tensor([[0.2573, 0.5918, 0.2013, 0.9897],
        [0.1386, 0.8789, 0.9312, 0.3238],
        [0.6858, 0.4690, 0.3803, 0.2955]])


なお、transposeは見え方のみ変える関数で、データの入れ替えは行いません。

参考：TensorはStorageという名の一次元配列でデータを保持しており、それをoffset, strideという変数の値を用いて行列のように見せています。見え方を変えるとはoffset, strideを変更することで、データの入れ替えとはStorageを変更することを言います。[参考資料](https://ohke.hateblo.jp/entry/2019/11/30/230000)


view(y, x)で、y行x列のデータに変換することができます。
  - -1をどちらかに指定すると自動的に大きさから計算してくれますが、約数でないと変換できずエラーになります。
  - viewはデータの入れ替えは行わず見え方のみ操作する関数で、Storage上の並びは変更されません。

In [ ]:
x = torch.randn(4, 4) # 4×4の乱数行列を作成
y = x.view(16)  # 16次元の行列にサイズ変更
z = x.view(-1, 8) # -1を使うと、サイズが自動調整
print(x.size(), y.size(), z.size())
print(x, "\n", y, "\n", z, "\n")

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.6498,  1.4602, -0.7937, -0.7266],
        [ 1.7468,  0.2590,  0.3075, -0.5896],
        [ 1.2868, -0.3919, -0.6544, -0.8888],
        [-0.5944, -0.5710, -0.6808,  0.0649]]) 
 tensor([ 0.6498,  1.4602, -0.7937, -0.7266,  1.7468,  0.2590,  0.3075, -0.5896,
         1.2868, -0.3919, -0.6544, -0.8888, -0.5944, -0.5710, -0.6808,  0.0649]) 
 tensor([[ 0.6498,  1.4602, -0.7937, -0.7266,  1.7468,  0.2590,  0.3075, -0.5896],
        [ 1.2868, -0.3919, -0.6544, -0.8888, -0.5944, -0.5710, -0.6808,  0.0649]]) 



ただ、viewは一つだけ注意点があります。
それは、先述したように、viewは見え方のみ操作する関数なので、viewを適用するTensorのStorageオブジェクトの要素は、行列の左上から見て連続な要素順に並んでいる必要があります。

例えば、転置したTensorに対してviewでサイズ数を変更したい場合、そのまま実行すると下記のようにエラーになります。transposeにより見え方のみ変更されて、行列に対するStorageの並びが不連続となっているときに、再度見え方のみ変更しようとしてしまうからです。

In [ ]:
torch.transpose(x, 0, 1).view(-1, 2)

RuntimeError: ignored

したがって、以下のように、viewの前にcontiguous()を呼び出すとStorageの要素が行列に対して連続になるように並び替えられ、そのあとにviewすると回避できます。

In [ ]:
torch.transpose(x, 0, 1).contiguous().view(-1, 2)

reshapeは、viewと同様にテンソルのリサイズができ、contiguous関数を必要としません。この理由は、データのコピーを作っている（=Storageを生成しなおす）からで、メモリ自体は消費しますが、エラーにはなりません。

In [ ]:
torch.transpose(x, 0, 1).reshape(-1, 2)

**PyTorchテンソルの要素の型**

テンソルの中に含める数値には、PyTorch独自のデータ型（`torch.dtypes`）が与えられていますが、あるテンソルに含まれる全要素は全て同じデータ型である必要があります。

以下の型が準備されていますが、ほとんどの場合、`torch.float`か`torch.int`を用います。

データ型 | dtype属性への記述 | 対応するPython／NumPy（np）のデータ型
---------|-----------------|--------------------------------
Boolean（真偽値）|torch.bool|bool／np.bool
8-bitの符号なし整数|torch.uint8|int／np.uint8
8-bitの符号付き整数|torch.int8|int／np.int8
16-bitの符号付き整数|torch.int16 ／ torch.short|int／np.uint16
32-bitの符号付き整数|torch.int32 ／ torch.int|int／np.uint32
64-bitの符号付き整数|torch.int64 ／ torch.long|int／np.uint64
16-bitの浮動小数点|torch.float16 ／ torch.half|float／np.float16
32-bitの浮動小数点|torch.float32 ／ torch.float|float／np.float32
64-bitの浮動小数点|torch.float64 ／ torch.double|float／np.float64


**テンソルの結合** 


``torch.cat``を使用することで、テンソルを特定の次元に沿って結合させることができます（詳細は[こちら](https://pytorch.org/docs/stable/generated/torch.stack.html)をご覧ください）。

``torch.cat``とは微妙に異なるテンソル結合演算である[``torch.stack``](https://pytorch.org/docs/stable/generated/torch.stack.html)も確認しておいてください。



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

**算術演算**



**足し算の例**

In [ ]:
x = torch.ones(5, 3)
y = torch.ones(5, 3)
x+y

torchが準備するaddメソッドもありますが、演算子を用いたほうが分かりやすく、おすすめです。

In [ ]:
torch.add(x, y)

また、結果を格納するテンソルを準備して、addメソッドを使うことで出力先を指定することができますが、下に示す演算子を使った例のほうが分かりやすいかもしれません。

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

In [ ]:
x = torch.ones(5, 3)
y = torch.ones(5, 3)
y1 = y
y2 = y
y1.add(x)   # in-placeでないメソッド
y2 = y2 + x  # in-placeでないメソッド
print(y)     # yは変更されない
print(y1)
print(y2)

余談ですが、Pythonでは、in-placeのメソッドとin-placeでないメソッドがあります。下の`y2 += x`や`add_()`はin-placeですが、上の`y = y + x`や`add()`はin-placeでないメソッドです。

これらの違いは、y1やy2に代入したyの値が、y1やy2の変更と一緒に変更されるかされないかの違いになっています。

上と下の例で見比べてみましょう。

In [ ]:
x = torch.ones(5, 3)
y = torch.ones(5, 3)
y1 = y
y2 = y
y1.add_(x)   # in-placeなメソッド
y2 += x      # in-placeなメソッド
print(y)     # yも変更される
print(y1)
print(y2)

【注意】


in-place操作はメモリを節約できますが、演算履歴が失われてしまうため、微分を計算する際には問題となります。

そのため、そのような微分を求める場面ではin-place操作の使用は推奨されていません。

**掛け算の例**

2つのテンソル行列の掛け算です。y1,y2は同じ値になります。

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
data = [[2, 3],[4, 5]]
y_data = torch.tensor(data)
y1 = x_data @ y_data
y2 = x_data.matmul(y_data)
print(y1)
print(y2)

こちらは要素ごとの積を求めます。z1,z2は同じ値になります。

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
data = [[2, 3],[4, 5]]
y_data = torch.tensor(data)
z1 = x_data * y_data
z2 = x_data.mul(y_data)
print(z1)
print(z2)

**1要素のテンソル** 

1要素のテンソル（テンソルの全要素を足し算する等をした結果生まれます）を扱う場合には、``.item()``を使用することでPythonの数値型変数に変換できます。




In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
agg = x_data.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

# 3. TensorとNumpyの相互変換
3章では、PyTorch特有のTensorと、Pythonで一般的に数式演算で用いられるNumPyの変換方法について説明します。<br>


## TensorからNumPyへの変換
まず、TensorをNumPyに変換するには、numpy()メソッドを使えば簡単に変換できます。

In [ ]:
import torch
x= torch.tensor([1,2,3,4,5,6])
print(x)
print(x.type())
y = x.numpy() #TensorをNumpyに変換
print(y)
print(type(y))

tensor([1, 2, 3, 4, 5, 6])
torch.LongTensor
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


尚、基本演算の部分と同様の議論になリますが、add_() を用いてxを変更するとyも一緒に変更されてしまうことに注意が必要です。これはadd_()がin-placeなメソッドであることが理由です。in-placeな方法による変更が難しいと感じるのであれば、not in-placeなadd()を用いても良いかもしれません。その他のin-placeな記述で有名なものとしてはy+=xのように「+=」を用いた記述方法があります。「y=y+x」と「y+=x」は同じことであるという文献を多々見ますが、厳密には異なる方法であるということを頭に入れておくと良いと思います。<br><br>

※in-placeとは？<br>
x.add_(1)やy+=xのように関数の適用や値の代入などを行う際，元のオブジェクトxの要素も変更されること。

In [ ]:
#in-placeなadd_()メソッドを用いた場合
x= torch.tensor([1,2,3,4,5,6])
y = x.numpy() #TensorをNumpyに変換
x.add_(1)
print("x:",x)
print("y:",y)

x: tensor([2, 3, 4, 5, 6, 7])
y: [2 3 4 5 6 7]


In [ ]:
#in-placeなadd()メソッドを用いた場合
x= torch.tensor([1,2,3,4,5,6])
y = x.numpy() #TensorをNumpyに変換
x = x.add(1)
print("x:",x)
print("y:",y)

x: tensor([2, 3, 4, 5, 6, 7])
y: [1 2 3 4 5 6]


In [ ]:
#補足　「x+=y」の形式を用いた場合
x= torch.tensor([1,2,3,4,5,6])
y = x.numpy() #TensorをNumpyに変換
x+=1
print("x:",x)
print("y:",y)

x: tensor([2, 3, 4, 5, 6, 7])
y: [2 3 4 5 6 7]


In [ ]:
#補足　「x=x+y」の形式を用いた場合
x= torch.tensor([1,2,3,4,5,6])
y = x.numpy() #TensorをNumpyに変換
x = x+1
print("x:",x)
print("y:",y)

x: tensor([2, 3, 4, 5, 6, 7])
y: [1 2 3 4 5 6]


## NumPyからTensorへの変換
NumPyをTensorに変換するには、from_numpy()メソッドを用います。

In [ ]:
import numpy as np
import torch
x= np.array([1,2,3,4,5,6])
y = torch.from_numpy(x)
print(x)
print(type(x))
print(y)
print(y.type())

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5, 6])
torch.LongTensor


尚、一般的にPyTorchではtorch.floatを用います。そのため、以下のようにnumpyでfloat32にキャストしてから利用する方法を覚えておくと良いでしょう。

In [ ]:
x= np.array([1,2,3,4,5,6])
y = torch.from_numpy(x.astype(np.float32))
print(x)
print(type(x))
print(y)
print(y.type())

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
tensor([1., 2., 3., 4., 5., 6.])
torch.FloatTensor


# 4. GPUとCPUの使い分け
4章では、PyTorchにおいてGPUを用いる際に必要となるGPUの指定方法について説明します。<br>
GPUを使用する前に、まず以下のようにGPUが搭載されているが、どのGPUが用いられているのか確認します。

In [ ]:
import torch
if torch.cuda.is_available():
  print(f'GPUデバイス数： {torch.cuda.device_count()}')
  print(f'現在のGPUデバイス番号： {torch.cuda.current_device()}')
  print(f'1番目のGPUデバイス名： {torch.cuda.get_device_name(0)}')
else:
  print('GPU使用不可')

GPUデバイス数： 1
現在のGPUデバイス番号： 0
1番目のGPUデバイス名： Tesla T4


このように、Google CoraboratoryではNVIDIA Teslaが使用できることが分かります。<br>
これを踏まえ、GPUを明示的に使用する方法を見ていきます。まず、以下のようにdeviceという変数にCPU、GPUどのデバイスを用いるかを格納します。

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #デバイスとしてGPU(cuda)かCPUか判定
print("デバイスの種類：",device)

デバイスの種類： cuda


このように、deviceという変数にデバイスの種類を格納しました。そして、GPU上でテンソル計算を行うためには、

- テンソルをdeviceを指定してGPU上で生成
- テンソルをdeviceを指定してGPU上に送る
  - to(device)で移動

のどちらかを行う必要があります。上記の2つは以下のように実現することができます。

In [ ]:
#GPU上でテンソル作成
x = torch.ones(2,3,device = device) #deviceを指定してGPU上でテンソル作成
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [ ]:
#CPU上でテンソル作成、GPUに送る
x = torch.ones(2,3) #CPU上でテンソル作成
print(x,x.device)
x = x.to(device) #GPUにテンソル送る
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) cpu
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


このように、テンソルをデバイス（CPU、GPU）を明示して作成することで、用いるデバイスを容易に切り替えることができます。<br>
そのため、CPU演算で十分の場合にはCPU、学習などGPU演算により効率性の上がるものはGPUを指定することで、効率的な処理が実現できます。<br>
尚、GPUに生成されたテンソルを取り出しndarray形式に変換する際には注意が必要です。先に説明した方法でndarray形式に変更しようとすると、以下のようなエラーが生じます。

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #デバイスとしてGPU(cuda)かCPUか判定
x = torch.ones(2,3) #CPU上でテンソル作成
x = x.to(device) #GPUにテンソル送る
y = x.numpy()
print(y,type(y))

TypeError: ignored

このようなエラーを解消するためには、以下のように`to("cpu").detach().numpy()`と記述することで、CPUに送ることを明示的に指定して取り出す必要があります。

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #デバイスとしてGPU(cuda)かCPUか判定
x = torch.ones(2,3) #CPU上でテンソル作成
x = x.to(device) #GPUにテンソル送る
y = x.to("cpu").detach().numpy()
print(x,x.type())
print(y,type(y))

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0') torch.cuda.FloatTensor
[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


※ 本資料は、[Pytorch公式のチュートリアル](https://yutaroogawa.github.io/pytorch_tutorials_jp/)を参考に作成致しました。
本資料には記載していない、さらに詳しい内容も公式チュートリアルには記載されていますので、興味ある方は調べてみてください。
